[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "employee_disciplinary_app"
version = "0.0.1"
description = "Employee Disciplinary Action Report for ERPNext"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
 
[tool.bench]
frappe-dependencies = [
  "frappe>=15.0.0,<17.0.0",
  "erpnext>=15.0.0,<17.0.0",
  "hrms>=15.0.0,<17.0.0"
]
